#!/bin/bash
[[ -z $1 ]] && echo "Por favor, escreva uma palavra para pesquisar no dicionário!" && echo "Uso: dicio-cli [PALAVRA]" && exit

WORD=$(echo $1 | tr '[:lower:]' '[:upper:]')
WORD_TO_SEARCH=$(echo $1 | tr '[:upper:]' '[:lower:]')
declare -A COLORS
COLORS=([YELLOW]='\033[1;33m' [MAGENTA]='\033[1;35m' [BLUE]='\033[0;36m' [WHITE]='\033[1;37m' [GRAY]='\033[0;37m')
current_definition=0

get_word_definition() {
  DOM_WORD_DEFINITION='<p itemprop="description" class="significado textonovo">'
  WORD_DEFINITION=$(curl "https://www.dicio.com.br/${WORD_TO_SEARCH}/" | grep "${DOM_WORD_DEFINITION}")
}

remove_paragraph() {
  WORD_DEFINITION=$(echo ${WORD_DEFINITION} | sed s/"${DOM_WORD_DEFINITION}"//g | sed s/'<\/p>'//g | sed s/'<br \/>'//g)
}

stylize_tags() {
  WORD_DEFINITION=$(echo ${WORD_DEFINITION} | sed s/'<span class="tag">'/" \\${COLORS[YELLOW]}"/g | sed s/']<\/span>'/"]\\${COLORS[WHITE]}"/g)
  WORD_DEFINITION="$(echo ${WORD_DEFINITION} | sed s/'<span class="cl">'/"\\${COLORS[MAGENTA]}|"/g | sed s/'<\/span>'/\\"${COLORS[WHITE]} |"/g | awk -F'[|]' '{ print $0}')"
  WORD_DEFINITION=$(echo ${WORD_DEFINITION} | sed s/'<span class="etim">'/\\${COLORS[GRAY]}/g | sed s/'<i>'//g | sed s/'<\/i>).'/").\\${COLORS[WHITE]}"/g)
}

format_word_definition() {
  remove_paragraph
  stylize_tags
  DEFINITIONS=$(echo ${WORD_DEFINITION} | sed s/'<span>'/" "/g | sed s/"<\/span>"/" | "/g | awk -F'[|]' '{ print $0 }')
}

print_definitions() {
  current_definition=$((${current_definition}+1))
  DEFINITION=$(echo ${DEFINITIONS} | awk -v current_definition="$current_definition" -F'[|]' '{ print $current_definition }')
}

get_word_definition
format_word_definition

clear
echo -e "${COLORS[BLUE]}${WORD}${COLORS[WHITE]}"
echo "Significado de ${WORD}"
echo "-----------------------------------------"
while :
do
  print_definitions
  
  [[ ${DEFINITION} == '' ]] && break
  [[ ${DEFINITION} != '\033[1;35m' ]] && echo -e " - $DEFINITION"
  [[ ${DEFINITION} == '\033[1;35m' ]] && echo -e "\033[1;35m"
done
